INDICATORS = list("Age of Inventory (Public)"="AOIP",
              "Buyer Seller Index"="BSI",
              "Days on Zillow (Public)"="DOZP",
              "Home Sales (NSA)"="SALES",
              "Home Sales (SA)"="SASALES",
              "Home Sold As Foreclosure - Ratio - All Homes"="HSAFRAL",
              "Inventory Measure (Public)"="IMP",
              "Inventory Measure - SSA (Public)"="IMSP",
              "Inventory Measure - Tiers (Public)"="IMTP",
              "Listings Price Cuts (SA) All Homes"="LPCSAL",
              "Listings Price Cuts (SA) Bottom Tier"="LPCSBT",
              "Listings Price Cuts (SA) Condominiums"="LPCSCO",
              "Listings Price Cuts (SA) Middle Tier"="LPCSMT",
              "Listings Price Cuts (SA) Single-Family Residence"="LPCSSF",
              "Listings Price Cuts (SA) Top Tier"="LPCSTT",
              "Market Health Index"="MHI",
              "Median Listing Price - All Homes"="MLPAH",
              "Median Listing Price - Condo/Co-op"="MLPCC",
              "Median Listing Price - Duplex/Triplex"="MLPDT",
              "Median Listing Price - Five Or More Bedrooms"="MLP5B",
              "Median Listing Price - Four Bedrooms"="MLP4B",
              "Median Listing Price - One Bedroom"="MLP1B",
              "Median Listing Price - Single-Family Residence"="MLPSF",
              "Median Listing Price - Three Bedrooms"="MLP3B",
              "Median Listing Price - Two Bedrooms"="MLP2B",
              "Median Listing Price Per Square Foot - All Homes"="MLPFAH",
              "Median Listing Price Per Square Foot - Condo/Co-op"="MLPFCC",
              "Median Listing Price Per Square Foot - Duplex/Triplex"="MLPFDT",
              "Median Listing Price Per Square Foot - Five Or More Bedrooms"="MLPF5B",
              "Median Listing Price Per Square Foot - Four Bedrooms"="MLPF4B",
              "Median Listing Price Per Square Foot - One Bedroom"="MLPF1B",
              "Median Listing Price Per Square Foot - Single-Family Residence"="MLPFSF",
              "Median Listing Price Per Square Foot - Three Bedrooms"="MLPF3B",
              "Median Listing Price Per Square Foot - Two Bedrooms"="MLPF2B",
              "Median Price Cut Dollar - All Homes"="MPCDAH",
              "Median Price Cut Dollar - Condo"="MPCDCO",
              "Median Price Cut Dollar - Single-Family Residence"="MPCDSF",
              "Median Price Of Reduction - All Homes"="MPPRAH",
              "Median Price Of Reduction - Condo"="MPPRCO",
              "Median Price Of Reduction - Single-Family Residence"="MPPRSF",
              "Median Rental Price - All Homes"="MRPAH",
              "Median Rental Price - Condo/Co-op"="MRPCC",
              "Median Rental Price - Duplex/Triplex"="MRPDT",
              "Median Rental Price - Five Or More Bedrooms"="MR51B",
              "Median Rental Price - Four Bedrooms"="MRP4B",
              "Median Rental Price - Multi-Family Residence"="MRPMF",
              "Median Rental Price - One Bedroom"="MRP1B",
              "Median Rental Price - Single-Family Residence"="MRPSF",
              "Median Rental Price - Studio"="MRPST",
              "Median Rental Price - Three Bedrooms"="MRP3B",
              "Median Rental Price - Two Bedrooms"="MRP2B",
              "Median Rental Price Per Square Foot - All Homes"="MRPFAH",
              "Median Rental Price Per Square Foot - Condo/Co-op"="MRPFCC",
              "Median Rental Price Per Square Foot - Duplex/Triplex"="MRPFDT",
              "Median Rental Price Per Square Foot - Five Or More Bedrooms"="MRPF5B",
              "Median Rental Price Per Square Foot - Four Bedrooms"="MRPF4B",
              "Median Rental Price Per Square Foot - Multi-Family Residence"="MRPFMF",
              "Median Rental Price Per Square Foot - One Bedroom"="MRPF1B",
              "Median Rental Price Per Square Foot - Single-Family Residence"="MRPFSF",
              "Median Rental Price Per Square Foot - Studio"="MRPFST",
              "Median Rental Price Per Square Foot - Three Bedrooms"="MRPF3B",
              "Median Rental Price Per Square Foot - Two Bedrooms"="MRPF2B",
              "Median Sold Price - All Homes"="MSPAH",
              "Median Sold Price Per Square Foot - All Homes"="MSPFAH",
              "Median Sold Price Per Square Foot - Condo"="MSPFCO",
              "Median Sold Price Per Square Foot - Single-Family Residence"="MSPFSF",
              "Median Value Per Square Foot - All Homes"="MVALFAH",
              "NF Sales"="NFS",
              "Percent Of Homes Decreasing In Values - All Homes"="PHDVAH",
              "Percent Of Homes Increasing In Values - All Homes"="PHIVAH",
              "Percent Of Homes Selling For Gain - All Homes"="PHSGAH",
              "Percent Of Homes Selling For Loss - All Homes"="PHSLAH",
              "Percent Of Listings With Price Reductions - All Homes"="PLPRAH",
              "Percent Of Listings With Price Reductions - Bottom Tier"="PLPRBT",
              "Percent Of Listings With Price Reductions - Condo"="PLPRCO",
              "Percent Of Listings With Price Reductions - Middle Tier"="PLPRMT",
              "Percent Of Listings With Price Reductions - Single-Family Residence"="PLPRSF",
              "Percent Of Listings With Price Reductions - Top Tier"="PLPRTT",
              "Percent Transactions That Are Previously Foreclosured Homes - All Homes"="PTPFHAH",
              "Price To Rent Ratio - All Homes"="PRRAH",
              "Turnover - All Homes"="TURNAH",
              # "Unsold Renos - All Homes"="USRAH",
              "Zillow Home Value Index - All Homes"="ZHVIAH",
              "Zillow Home Value Index - All Homes"="ZHVISAH",
              "Zillow Home Value Index - Bottom Tier Year-Over-Year"="ZHVIBTY",
              "Zillow Home Value Index - Bottom Tier"="ZHVIBT",
              "Zillow Home Value Index - Condo"="ZHVICO",
              "Zillow Home Value Index - Five Or More Bedrooms"="ZHVI5B",
              "Zillow Home Value Index - Four Bedrooms"="ZHVI4B",
              "Zillow Home Value Index - Middle Tier - Year-Over-Year"="ZHVIMTY",
              "Zillow Home Value Index - Middle Tier"="ZHVIMT",
              "Zillow Home Value Index - One Bedroom"="ZHVI1B",
              "Zillow Home Value Index - Single-Family Residence"="ZHVISF",
              "Zillow Home Value Index - Three Bedrooms"="ZHVI3B",
              "Zillow Home Value Index - Top Tier - Year-Over-Year"="ZHVITTY",
              "Zillow Home Value Index - Top Tier"="ZHVITT",
              "Zillow Home Value Index - Two Bedrooms"="ZHVI2B",
              "Zillow Rental Index - All Homes Plus Multi-Family Summary"="ZRIAHMFS",
              "Zillow Rental Index - All Homes Plus Multi-Family"="ZRIAHMF",
              "Zillow Rental Index - All Homes Summary"="ZRIAHS",
              "Zillow Rental Index - All Homes"="ZRIAH",
              "Zillow Rental Index - Multi-Family Residence Summary"="ZRIMFRRS",
              "Zillow Rental Index - Multi-Family Residence"="ZRIMFRR",
              "Zillow Rental Index - Single-Family Residence Summary"="ZRISFRRS",
              "Zillow Rental Index - Single-Family Residence"="ZRISFRR",
              "Zillow Rental Index Per Square Foot - All Homes"="ZRIFAH")

INDICATORS_NAMES = c("Age of Inventory (Public)",
                     "Buyer Seller Index",
                     "Days on Zillow (Public)",
                     "Home Sales (NSA)",
                     "Home Sales (SA)",
                     "Home Sold As Foreclosure - Ratio - All Homes",
                     "Inventory Measure (Public)",
                     "Inventory Measure - SSA (Public)",
                     "Inventory Measure - Tiers (Public)",
                     "Listings Price Cuts (SA) All Homes",
                     "Listings Price Cuts (SA) Bottom Tier",
                     "Listings Price Cuts (SA) Condominiums",
                     "Listings Price Cuts (SA) Middle Tier",
                     "Listings Price Cuts (SA) Single-Family Residence",
                     "Listings Price Cuts (SA) Top Tier",
                     "Market Health Index",
                     "Median Listing Price - All Homes",
                     "Median Listing Price - Condo/Co-op",
                     "Median Listing Price - Duplex/Triplex",
                     "Median Listing Price - Five Or More Bedrooms",
                     "Median Listing Price - Four Bedrooms",
                     "Median Listing Price - One Bedroom",
                     "Median Listing Price - Single-Family Residence",
                     "Median Listing Price - Three Bedrooms",
                     "Median Listing Price - Two Bedrooms",
                     "Median Listing Price Per Square Foot - All Homes",
                     "Median Listing Price Per Square Foot - Condo/Co-op",
                     "Median Listing Price Per Square Foot - Duplex/Triplex",
                     "Median Listing Price Per Square Foot - Five Or More Bedrooms",
                     "Median Listing Price Per Square Foot - Four Bedrooms",
                     "Median Listing Price Per Square Foot - One Bedroom",
                     "Median Listing Price Per Square Foot - Single-Family Residence",
                     "Median Listing Price Per Square Foot - Three Bedrooms",
                     "Median Listing Price Per Square Foot - Two Bedrooms",
                     "Median Price Cut Dollar - All Homes",
                     "Median Price Cut Dollar - Condo",
                     "Median Price Cut Dollar - Single-Family Residence",
                     "Median Price Of Reduction - All Homes",
                     "Median Price Of Reduction - Condo",
                     "Median Price Of Reduction - Single-Family Residence",
                     "Median Rental Price - All Homes",
                     "Median Rental Price - Condo/Co-op",
                     "Median Rental Price - Duplex/Triplex",
                     "Median Rental Price - Five Or More Bedrooms",
                     "Median Rental Price - Four Bedrooms",
                     "Median Rental Price - Multi-Family Residence",
                     "Median Rental Price - One Bedroom",
                     "Median Rental Price - Single-Family Residence",
                     "Median Rental Price - Studio",
                     "Median Rental Price - Three Bedrooms",
                     "Median Rental Price - Two Bedrooms",
                     "Median Rental Price Per Square Foot - All Homes",
                     "Median Rental Price Per Square Foot - Condo/Co-op",
                     "Median Rental Price Per Square Foot - Duplex/Triplex",
                     "Median Rental Price Per Square Foot - Five Or More Bedrooms",
                     "Median Rental Price Per Square Foot - Four Bedrooms",
                     "Median Rental Price Per Square Foot - Multi-Family Residence",
                     "Median Rental Price Per Square Foot - One Bedroom",
                     "Median Rental Price Per Square Foot - Single-Family Residence",
                     "Median Rental Price Per Square Foot - Studio",
                     "Median Rental Price Per Square Foot - Three Bedrooms",
                     "Median Rental Price Per Square Foot - Two Bedrooms",
                     "Median Sold Price - All Homes",
                     "Median Sold Price Per Square Foot - All Homes",
                     "Median Sold Price Per Square Foot - Condo",
                     "Median Sold Price Per Square Foot - Single-Family Residence",
                     "Median Value Per Square Foot - All Homes",
                     "NF Sales",
                     "Percent Of Homes Decreasing In Values - All Homes",
                     "Percent Of Homes Increasing In Values - All Homes",
                     "Percent Of Homes Selling For Gain - All Homes",
                     "Percent Of Homes Selling For Loss - All Homes",
                     "Percent Of Listings With Price Reductions - All Homes",
                     "Percent Of Listings With Price Reductions - Bottom Tier",
                     "Percent Of Listings With Price Reductions - Condo",
                     "Percent Of Listings With Price Reductions - Middle Tier",
                     "Percent Of Listings With Price Reductions - Single-Family Residence",
                     "Percent Of Listings With Price Reductions - Top Tier",
                     "Percent Transactions That Are Previously Foreclosured Homes - All Homes",
                     "Price To Rent Ratio - All Homes",
                     "Turnover - All Homes",
                     # "Unsold Renos - All Homes",
                     "Zillow Home Value Index - All Homes",
                     "Zillow Home Value Index - All Homes",
                     "Zillow Home Value Index - Bottom Tier Year-Over-Year",
                     "Zillow Home Value Index - Bottom Tier",
                     "Zillow Home Value Index - Condo",
                     "Zillow Home Value Index - Five Or More Bedrooms",
                     "Zillow Home Value Index - Four Bedrooms",
                     "Zillow Home Value Index - Middle Tier - Year-Over-Year",
                     "Zillow Home Value Index - Middle Tier",
                     "Zillow Home Value Index - One Bedroom",
                     "Zillow Home Value Index - Single-Family Residence",
                     "Zillow Home Value Index - Three Bedrooms",
                     "Zillow Home Value Index - Top Tier - Year-Over-Year",
                     "Zillow Home Value Index - Top Tier",
                     "Zillow Home Value Index - Two Bedrooms",
                     "Zillow Rental Index - All Homes Plus Multi-Family Summary",
                     "Zillow Rental Index - All Homes Plus Multi-Family",
                     "Zillow Rental Index - All Homes Summary",
                     "Zillow Rental Index - All Homes",
                     "Zillow Rental Index - Multi-Family Residence Summary",
                     "Zillow Rental Index - Multi-Family Residence",
                     "Zillow Rental Index - Single-Family Residence Summary",
                     "Zillow Rental Index - Single-Family Residence",
                     "Zillow Rental Index Per Square Foot - All Homes")


STATES = list("Alabama"=3,
              "Alaska"=2,
              "Arizona"=5,
              "Arkansas"=4,
              "California"=6,
              "Colorado"=7,
              "Connecticut"=8,
              "Delaware"=10,
              "District of Columbia"=9,
              "Florida"=11,
              "Georgia"=12,
              "Hawaii"=13,
              "Idaho"=15,
              "Illinois"=16,
              "Indiana"=17,
              "Iowa"=14,
              "Kansas"=18,
              "Kentucky"=19,
              "Louisiana"=20,
              "Maine"=51,
              "Maryland"=22,
              "Massachusetts"=21,
              "Michigan"=23,
              "Minnesota"=24,
              "Mississippi"=26,
              "Missouri"=25,
              "Montana"=27,
              "Nebraska"=30,
              "Nevada"=34,
              "New Hampshire"=31,
              "New Jersey"=32,
              "New Mexico"=33,
              "New York"=35,
              "North Carolina"=28,
              "North Dakota"=29,
              "Ohio"=36,
              "Oklahoma"=37,
              "Oregon"=38,
              "Pennsylvania"=39,
              "Rhode Island"=40,
              "South Carolina"=41,
              "South Dakota"=52,
              "Tennessee"=42,
              "Texas"=43,
              "United States"=1,
              "Utah"=44,
              "Vermont"=46,
              "Virginia"=45,
              "Washington"=47,
              "West Virginia"=49,
              "Wisconsin"=48,
              "Wyoming"=50)
